pandapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("catalogue/", views.CatalogueView.as_view(), name='catalogue'),
    path("submit/", views.FileForm.as_view(), name='submit_form'),
]

pandjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("pandapp.urls")),
    path('admin/', admin.site.urls),
]

pandapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class TelephoneNumberCatalogue(models.Model):
    ods_file = models.FileField(upload_to="ods/", verbose_name="ods file", null=True)

    def get_absolute_url(self):
        return reverse("catalogue")

class TelephoneNumbers(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    telephone_number = models.PositiveBigIntegerField()

    def __str__(self):
        return f"Telephone number of {self.first_name} {self.last_name}"
    

pandapp/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.views.generic import CreateView, ListView
from .models import TelephoneNumberCatalogue, TelephoneNumbers
from django.conf import settings
import pandas as pd
import os

# Create your views here.
class CatalogueView(ListView):
    template_name = 'pandapp/catalogue.html'
    context_object_name = 'all_telephone_numbers'
    def get_queryset(self):
        return TelephoneNumbers.objects.all()

class FileForm(CreateView):
    model = TelephoneNumberCatalogue
    fields = "__all__"

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        try:
            path_file = os.path.join(settings.BASE_DIR, f"static/media/ods/{self.object.odt_file}")
            print(path_file)
            odt = TelephoneNumberCatalogue.objects.get(odt_file="ods/Untitled_1.ods")
            print(odt.odt_file)
            print("I found it")
        except:
            print("I did not find it")
        return super().form_valid(form)





# install pandas and odfpy
        

pandapp/templates/pandapp/catalogue.html
{% extends "base.html" %}

{% block title %}
Telephone directory
{% endblock %}

{% block main %}
<h1>Telephone directory</h1>
{% if not all_telephone_numbers %}
The telephone directory is empty. If you wish to add some telephone numbers please click on the button below.
{% endif %}
 <ul>
    {% for t in all_telephone_numbers %}
    <li>{{t.first_name}} {{t.last_name}} : {{t.telephone_number}}</li>
    {% endfor %}
 </ul>

 <a href="{% url 'submit_form' %}">
   <button type="button" class="btn btn-primary">
      Submit a file
   </button>
 </a>
 
{% endblock %}

pandapp/templates/pandapp/telephonenumbercatalogue_form.html
{% extends "base.html" %}

{% block title %}
Submit a file
{% endblock %}

{% block main %}
<h1>File submission</h1>
The ods file submitted should contain three columns : "first name", "last name" and "telephone number".
If it is not the case the ods file's telephone numbers will not be added to the telephone directory.
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <p>
            <label for="id_ods_file">ods file:</label>
            <input type="file" name="ods_file" required="" id="id_ods_file" class="form-control">
        </p>

        <button type="submit" class="btn btn-dark" >Submit your ods file</button>
    </form>

    <br><br>

    <a href="{% url 'catalogue' %}">
        <button type="button" class="btn btn-primary">
            Telephone directory
        </button>
    </a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %}
    </title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <!-- bootstrap 5.3.3 CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- bootstrap 5.3.3 CDN -->

</head>
<body>
    <div id="main_div">
        {% block main %}{% endblock %}
    </div>
</body>
</html>